### ISSUE TITLE
Unity3d

### ISSUE THREAD

**Issue by CornLizard** [useaible/RyskampLearningMachine#13]
Hello I'm trying to get your library running in Unity 2017 using .net framework 4.6. I recompiled the code to use any cpu and use framework 4.6. I tried with the normal 64 bit and framework 4.6.1 still the same issue. It is possible that it has something to do with Unity's use of mono. 

Looking at the source code of your library and error message I can see that it seems to be coming from somewhere in the RlmDbMgr class involving RlmDbEntities.

The unity code below and the error message below that

`using RLM;
using RLM.Enums;
using RLM.Models;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;
public class RLM_Test : MonoBehaviour {

    private string NETWORK_NAME = "my test";
    private RlmNetwork network;
    public void Start()
    {
        Debug.Log("RLM Test Unity");
        string dbName = "RLM_TestUnity_" + Guid.NewGuid().ToString("N");
        network = new RlmNetwork(dbName);
        network.DataPersistenceComplete += Network_DataPersistenceComplete;
        network.DataPersistenceProgress += Network_DataPersistenceProgress;

        if (!network.LoadNetwork(NETWORK_NAME))
        {
            List<RlmIO> inputs = new List<RlmIO>();
            inputs.Add(new RlmIO("input01", typeof(System.Boolean).ToString(), 0, 1, RlmInputType.Distinct));

            var outputs = new List<RlmIO>();
            outputs.Add(new RlmIO("output01", typeof(System.Boolean).ToString(), 0, 1));

            network.NewNetwork(NETWORK_NAME, inputs, outputs);
        }

        network.NumSessions = 100;
        network.StartRandomness = 30;
        network.EndRandomness = 0;
        network.MaxLinearBracket = 15;
        network.MinLinearBracket = 3;

        network.SessionStart();

        var cycleInputs = new List<RlmIOWithValue>();
        cycleInputs.Add(new RlmIOWithValue(network.Inputs.First(a => a.Name == "input01"), "0"));

        var cycle = new RlmCycle();
        var cycleOutcome = cycle.RunCycle(network, network.CurrentSessionID, cycleInputs, true);

        network.ScoreCycle(cycleOutcome.CycleOutput.CycleID, 0);

        network.SessionEnd(0);

    }

    private static void Network_DataPersistenceProgress(long processed, long total)
    {
        Debug.Log($"Data Persistence progress: {processed} / {total}");
    }

    private static void Network_DataPersistenceComplete()
    {
        Debug.Log("RLM Data Persistence done.");
    }
}
`

`SocketException: Could not resolve host '.'
System.Net.Dns.Error_11001 (System.String hostName) (at <f044fe2c9e7e4b8e91984b41f0cf0b04>:0)
System.Net.Dns.GetHostByName (System.String hostName) (at <f044fe2c9e7e4b8e91984b41f0cf0b04>:0)
System.Net.Dns.GetHostEntry (System.String hostNameOrAddress) (at <f044fe2c9e7e4b8e91984b41f0cf0b04>:0)
System.Net.Dns.GetHostAddresses (System.String hostNameOrAddress) (at <f044fe2c9e7e4b8e91984b41f0cf0b04>:0)
System.Net.Sockets.UdpClient.Connect (System.String hostname, System.Int32 port) (at <f044fe2c9e7e4b8e91984b41f0cf0b04>:0)
System.Net.Sockets.UdpClient..ctor (System.String hostname, System.Int32 port) (at <f044fe2c9e7e4b8e91984b41f0cf0b04>:0)
System.Data.SqlClient.SqlConnection+SqlMonitorSocket..ctor (System.String ServerName, System.String InstanceName) (at <2b29b830e1c04af3bbefdda978a65227>:0)
System.Data.SqlClient.SqlConnection.DiscoverTcpPortViaSqlMonitor (System.String ServerName, System.String InstanceName) (at <2b29b830e1c04af3bbefdda978a65227>:0)
System.Data.SqlClient.SqlConnection.ParseDataSource (System.String theDataSource, System.Int32& thePort, System.String& theServerName) (at <2b29b830e1c04af3bbefdda978a65227>:0)
System.Data.SqlClient.SqlConnection.Open () (at <2b29b830e1c04af3bbefdda978a65227>:0)
RLM.Database.RlmDbEntities.TryConnect (System.String connString) (at <38839b0c3e4641b08e1490da01e5b246>:0)
RLM.Database.RlmDbEntities.DetermineSQLConnectionString () (at <38839b0c3e4641b08e1490da01e5b246>:0)
RLM.Database.RlmDbEntities..cctor () (at <38839b0c3e4641b08e1490da01e5b246>:0)
Rethrow as TypeInitializationException: The type initializer for 'RLM.Database.RlmDbEntities' threw an exception.
RLM.Database.RlmDbBatchProcessor..ctor (System.String databaseName) (at <38839b0c3e4641b08e1490da01e5b246>:0)
RLM.Database.RlmDbMgr..ctor (System.String databaseName) (at <38839b0c3e4641b08e1490da01e5b246>:0)
RLM.Memory.Manager..ctor (RLM.Models.Interfaces.IRlmNetwork network, System.Boolean trackStats) (at <84c9e8d57ffc4bd499df418602e228bb>:0)
RLM.RlmNetwork.Initialize () (at <b8e81732ec8b4dca8117c0302e956dcc>:0)
RLM.RlmNetwork..ctor (System.String databaseName) (at <b8e81732ec8b4dca8117c0302e956dcc>:0)
RLM_Test.Start () (at Assets/RLM_Test.cs:17)
`

**Comment by randolph-useaible** [comment]
Hi Frosty,

Thank you for taking the time to report this issue.

The RLM, by default, targets .NET Framework 4.6.2 but judging from the exception I don't think recompiling it to a different framework target was the fix nor was the problem. From the Exception message you are getting, it is saying that it has a problem connecting to the Database server - _"SocketException: Could not resolve host '.' "_. 

It may only be a simple change to your connection string for the Server/Data Source setting to point to the correct server address instead of the . (dot). Please refer to our [wiki](https://github.com/useaible/RyskampLearningMachine/wiki/1.4.-Building-the-Solution#connection-strings) on how to change/override the connection string that the RLM uses to connect to SQL Server. Also, make sure your SQL Server is up and running and accessible from where you are currently testing your code.

Let me know how it goes. We are currently making improvements to the RLM and I apologize for the vague error messages you might be getting. We will include more descriptive error messages on later releases.

Thanks

**Comment by CornLizard** [comment]
Yeah I figured changing frameworks wouldn't do anything but it seemed worth a try!

Unity by default doesn't seem to use a .config file. If I add one it doesn't show up in the Unity Editor. I used the same code in Xenko Game Engine and it doesn't use a config file either. It worked without any issues. Is there anyway I can override it through direct code access? 

Maybe Unity it being blocked for some reason I'll look into that.

**Comment by randolph-useaible** [comment]
Currently, we don't have any API that allows you to change the connection string directly through code.

As a workaround, you could change the source if you have it or you could fork/clone our repository and edit the [RlmDbEntities class on line 47](https://github.com/useaible/RyskampLearningMachine/blob/e9b29b3883d2f9782501f826b916bfe4643bb19b/Core/RLM/RLM.Database/RlmDbEntities.cs#L47)  to:

`connStr = "Server=<your_server_here>;Database={{dbaseName}};Integrated Security=True;"`

Recompile it and use the new dlls on your project for now until the next release with new APIs to directly change the connection string.

> Maybe Unity it being blocked for some reason I'll look into that.

That would be interesting to investigate on considering on Xenko Game Engine using the defaults worked for you.

**Comment by CornLizard** [comment]
Well now it can find the server but the connection is closed down. So it appears to be blocked. I'm not sure where to go from here. I'm going to try the suggestion from this link http://answers.unity3d.com/questions/123876/cant-connect-from-unity-31-to-sql-server-express.html

New error message below

```
SocketException: An existing connection was forcibly closed by the remote host.

System.Net.Sockets.Socket.ReceiveFrom_nochecks_exc (System.Byte[] buf, System.Int32 offset, System.Int32 size, System.Net.Sockets.SocketFlags flags, System.Net.EndPoint& remote_end, System.Boolean throwOnError, System.Int32& error) (at <f044fe2c9e7e4b8e91984b41f0cf0b04>:0)
System.Net.Sockets.Socket.ReceiveFrom (System.Byte[] buffer, System.Int32 offset, System.Int32 size, System.Net.Sockets.SocketFlags socketFlags, System.Net.EndPoint& remoteEP) (at <f044fe2c9e7e4b8e91984b41f0cf0b04>:0)
System.Net.Sockets.Socket.ReceiveFrom (System.Byte[] buffer, System.Net.EndPoint& remoteEP) (at <f044fe2c9e7e4b8e91984b41f0cf0b04>:0)
System.Net.Sockets.UdpClient.Receive (System.Net.IPEndPoint& remoteEP) (at <f044fe2c9e7e4b8e91984b41f0cf0b04>:0)
System.Data.SqlClient.SqlConnection+SqlMonitorSocket.DiscoverTcpPort (System.Int32 timeoutSeconds) (at <2b29b830e1c04af3bbefdda978a65227>:0)
System.Data.SqlClient.SqlConnection.DiscoverTcpPortViaSqlMonitor (System.String ServerName, System.String InstanceName) (at <2b29b830e1c04af3bbefdda978a65227>:0)
System.Data.SqlClient.SqlConnection.ParseDataSource (System.String theDataSource, System.Int32& thePort, System.String& theServerName) (at <2b29b830e1c04af3bbefdda978a65227>:0)
System.Data.SqlClient.SqlConnection.Open () (at <2b29b830e1c04af3bbefdda978a65227>:0)
System.Data.Entity.Infrastructure.Interception.DbConnectionDispatcher.<Open>b__36 (System.Data.Common.DbConnection t, System.Data.Entity.Infrastructure.Interception.DbConnectionInterceptionContext c) (at <000f54522ad145bf987b3043022f9799>:0)
System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1[TInterceptor].Dispatch[TTarget,TInterceptionContext] (TTarget target, System.Action`2[T1,T2] operation, TInterceptionContext interceptionContext, System.Action`3[T1,T2,T3] executing, System.Action`3[T1,T2,T3] executed) (at <000f54522ad145bf987b3043022f9799>:0)
System.Data.Entity.Infrastructure.Interception.DbConnectionDispatcher.Open (System.Data.Common.DbConnection connection, System.Data.Entity.Infrastructure.Interception.DbInterceptionContext interceptionContext) (at <000f54522ad145bf987b3043022f9799>:0)
System.Data.Entity.SqlServer.SqlProviderServices+<>c__DisplayClass33.<UsingConnection>b__32 () (at <0025bc3e22524ba9a352d7f62faa5b3f>:0)
System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy+<>c__DisplayClass1.<Execute>b__0 () (at <0025bc3e22524ba9a352d7f62faa5b3f>:0)
System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult] (System.Func`1[TResult] operation) (at <0025bc3e22524ba9a352d7f62faa5b3f>:0)
Rethrow as TypeInitializationException: The type initializer for 'RLM.Database.RlmDbEntities' threw an exception.
RLM.Database.RlmDbBatchProcessor..ctor (System.String databaseName) (at <2a9609f645bb4431aad9beab1f9d253b>:0)
RLM.Database.RlmDbMgr..ctor (System.String databaseName) (at <2a9609f645bb4431aad9beab1f9d253b>:0)
RLM.Memory.Manager..ctor (RLM.Models.Interfaces.IRlmNetwork network, System.Boolean trackStats) (at <8107e0c148514403b8a7e3171fa5b779>:0)
RLM.RlmNetwork.Initialize () (at <05f36903ffc842b985255a34532cec82>:0)
RLM.RlmNetwork..ctor (System.String databaseName) (at <05f36903ffc842b985255a34532cec82>:0)
RLM_Test.Start () (at Assets/RLM_Test.cs:17)
```

**Comment by randolph-useaible** [comment]
Is the SQL Server running locally, on the same network, or on a remote machine?

I will need to do some tests and replicate this issue and figure out why it is throwing this exception.

For now, I will try to create a new branch where the RLM has an option to turn off the Data Persistence so you won't have to deal with any DB issues on your test while we fix the issue. This is actually in the pipeline for the next release but I can put up this new branch as a workaround for now as others might want to turn off data persistence just to test their own apps. Although, you won't have any of the learning data saved by turning it off. What that means is that you can't load and improve on any pre-existing RLM data and you have to use a new instance and learn it from scratch every time you run your app. Is this something you can work with in the short term?

**Comment by FrostyFeet1** [comment]
The SQL Server is running locally on my computer.

**Comment by CornLizard** [comment]
Ooops haha The server is running locally on my computer.
That would be awesome! I don't really need the data to persist right now. If it helps me continue on I won't object. Apparently the normal version of SQL works! Unity doesn't like SQL Express. There are still issues with the login but it should be solvable. 

```
SqlException: Login failed. The login is from an untrusted domain and cannot be used with Windows authentication.
System.Data.SqlClient.SqlConnection.ErrorHandler (System.Object sender, Mono.Data.Tds.Protocol.TdsInternalErrorMessageEventArgs e) (at <2b29b830e1c04af3bbefdda978a65227>:0)
Mono.Data.Tds.Protocol.Tds.OnTdsErrorMessage (Mono.Data.Tds.Protocol.TdsInternalErrorMessageEventArgs e) (at <d628d5ccba464c4289955269a67b59a0>:0)
Mono.Data.Tds.Protocol.Tds.ProcessMessage (Mono.Data.Tds.Protocol.TdsPacketSubType subType) (at <d628d5ccba464c4289955269a67b59a0>:0)
Mono.Data.Tds.Protocol.Tds.ProcessSubPacket () (at <d628d5ccba464c4289955269a67b59a0>:0)
Mono.Data.Tds.Protocol.Tds.NextResult () (at <d628d5ccba464c4289955269a67b59a0>:0)
Mono.Data.Tds.Protocol.Tds.SkipToEnd () (at <d628d5ccba464c4289955269a67b59a0>:0)
Mono.Data.Tds.Protocol.Tds70.Connect (Mono.Data.Tds.Protocol.TdsConnectionParameters connectionParameters) (at <d628d5ccba464c4289955269a67b59a0>:0)
Mono.Data.Tds.Protocol.Tds80.Connect (Mono.Data.Tds.Protocol.TdsConnectionParameters connectionParameters) (at <d628d5ccba464c4289955269a67b59a0>:0)
System.Data.SqlClient.SqlConnection.Open () (at <2b29b830e1c04af3bbefdda978a65227>:0)
Rethrow as TypeInitializationException: The type initializer for 'RLM.Database.RlmDbEntities' threw an exception.
RLM.Database.RlmDbBatchProcessor..ctor (System.String databaseName) (at <5e82133220034dad8b5fd8b042eb2f0f>:0)
RLM.Database.RlmDbMgr..ctor (System.String databaseName) (at <5e82133220034dad8b5fd8b042eb2f0f>:0)
RLM.Memory.Manager..ctor (RLM.Models.Interfaces.IRlmNetwork network, System.Boolean trackStats) (at <dbb673f3dd6d4edd8bfc294f271be009>:0)
RLM.RlmNetwork.Initialize () (at <de1cbe818afe4319bddd4dc9dbd059a5>:0)
RLM.RlmNetwork..ctor (System.String databaseName) (at <de1cbe818afe4319bddd4dc9dbd059a5>:0)
RLM_Test.Start () (at Assets/RLM_Test.cs:17)

```

**Comment by randolph-useaible** [comment]
That's great! We will take note of that.

For the login issue, I think you need to change your Connection string, specifically remove the `Integrated Security=True;` and change it to `User=<your_username>;Password=<your_password>`. Usually, you can just use **sa** account if you have it set up. Here is an [article](https://sudeeptaganguly.wordpress.com/2010/04/20/how-to-enable-sa-account-in-sql-server/) to get you started on that.

I think we are close to solving this issue so I might hold up on that new branch. Otherwise, I'll go ahead and build that.

**Comment by CornLizard** [comment]
It's producing another error. I tried the sa user and my own custom user nothing worked it's like its not receiving the password. anyways I'm tired and will have to come back to this tomorrow. 

From what I can tell the connection string is correct. My SQL skills are lacking.
connStr = $"Server=Server;Database={{dbaseName}};User=Username;Password=Password; ";

If you build the project that would be cool but I can wait for a proper build :) really happy that you came out with a c# compatible AI library! 

```

SqlException: Login failed for user 'Username'.
System.Data.SqlClient.SqlConnection.ErrorHandler (System.Object sender, Mono.Data.Tds.Protocol.TdsInternalErrorMessageEventArgs e) (at <2b29b830e1c04af3bbefdda978a65227>:0)
Mono.Data.Tds.Protocol.Tds.OnTdsErrorMessage (Mono.Data.Tds.Protocol.TdsInternalErrorMessageEventArgs e) (at <d628d5ccba464c4289955269a67b59a0>:0)
Mono.Data.Tds.Protocol.Tds.ProcessMessage (Mono.Data.Tds.Protocol.TdsPacketSubType subType) (at <d628d5ccba464c4289955269a67b59a0>:0)
Mono.Data.Tds.Protocol.Tds.ProcessSubPacket () (at <d628d5ccba464c4289955269a67b59a0>:0)
Mono.Data.Tds.Protocol.Tds.NextResult () (at <d628d5ccba464c4289955269a67b59a0>:0)
Mono.Data.Tds.Protocol.Tds.SkipToEnd () (at <d628d5ccba464c4289955269a67b59a0>:0)
Mono.Data.Tds.Protocol.Tds70.Connect (Mono.Data.Tds.Protocol.TdsConnectionParameters connectionParameters) (at <d628d5ccba464c4289955269a67b59a0>:0)
Mono.Data.Tds.Protocol.Tds80.Connect (Mono.Data.Tds.Protocol.TdsConnectionParameters connectionParameters) (at <d628d5ccba464c4289955269a67b59a0>:0)
System.Data.SqlClient.SqlConnection.Open () (at <2b29b830e1c04af3bbefdda978a65227>:0)
Rethrow as TypeInitializationException: The type initializer for 'RLM.Database.RlmDbEntities' threw an exception.
RLM.Database.RlmDbBatchProcessor..ctor (System.String databaseName) (at <6ea0cdccb86d46d0856775bc616d6bb1>:0)
RLM.Database.RlmDbMgr..ctor (System.String databaseName) (at <6ea0cdccb86d46d0856775bc616d6bb1>:0)
RLM.Memory.Manager..ctor (RLM.Models.Interfaces.IRlmNetwork network, System.Boolean trackStats) (at <8be1d7f3a8a1467a9a3169d48955d5d8>:0)
RLM.RlmNetwork.Initialize () (at <036d61c3eae246829dda498d7046861a>:0)
RLM.RlmNetwork..ctor (System.String databaseName) (at <036d61c3eae246829dda498d7046861a>:0)
RLM_Test.Start () (at Assets/RLM_Test.cs:17)

```

**Comment by randolph-useaible** [comment]
I would be glad to help you more on this and we are near solving the problem. I think it is best we communicate through email and maybe we can do some screen share to get this problem solved and if you need any support going forward then it would be easier for you to reach us directly. We are interested on what you are doing with the RLM and encourage others to do the same which is to apply it on their own projects. So, here is my company email  _firstname.lastname@domain.com_ where 
firstname = randolph
lastname = bangay
domain = useaible
It has a . (dot) in between the firstname and the lastname. I'm sorry to have to break it apart like that as I don't want spam bots getting hold of this email and sending any junk to it. :)

For the build with persistence option, I'm actually going to go ahead on that and the bleeding edge version of the RLM should be available in a couple of hours as a separate branch here on our github repo.

**Comment by randolph-useaible** [comment]
The [RLM dev-branch](https://github.com/useaible/RyskampLearningMachine/tree/dev-branch) has been uploaded to our github repository and is ready for you to try out. So, to disable the Persistence you can pass in a `boolean` to the `RlmNetwork` constructor like so:

`var network = new RlmNetwork(false);`

This should allow you to continue with your work without having to worry about the underlying database persistence feature.

**Comment by CornLizard** [comment]
Thank you very much! I'm currently working on something with the latest library update. I will follow up through email soon. Things are coming along very well. :)
