### ISSUE TITLE
Only Windows? Why?

### ISSUE THREAD

**Issue by subzerofun** [useaible/RyskampLearningMachine#8]
I hope that you're aware that most AI/machine learning developers use Linux, although macOS is also popular due to its "Unix-ness". How should people be able to verify your claims if you only provide Visual Studio code? You didn't even think about including a notice for non-Windows users in your [guide](https://github.com/useaible/RyskampLearningMachine/blob/master/Documentation/Developer%20Guide.pdf).

Do you know any machine learning frameworks/tools that complete ignore the OS(es) of their core user base? 

Then you invite people to test your examples, like the "[maze](http://useaible.com/machine-learning-challenge/maze/)" – but only if they register? That's a strange attitude.

**Comment by gino-useaible** [comment]
Hi subzerofun,

We really appreciate the feedback. I strongly agree that Linux is a good direction for us and I'm happy to say we're working towards that. This is the same with the Visual Studio code, however, we have python code available too, with sample apps. It's on our Developer's Guide.

On the point about the registration, thank you for you thoughts on this. I'll discuss with the team on it and decide on an action plan.

We appreciate you taking the time to point this out.
